#!/bin/sh

cd ~
curl --remote-name https://raw.githubusercontent.com/gallaway/mac_deploy/master/mac
curl --remote-name https://raw.githubusercontent.com/gallaway/mac_deploy/master/Brewfile
/usr/bin/env bash mac 2>&1 | tee ~/laptop.log
